### ISSUE TITLE
Broken lib/util.js published

### ISSUE THREAD

**Issue by papandreou** [7rulnik/source-map-js#11]
Looks like https://github.com/7rulnik/source-map-js/blob/895d9cc038968d3eef5edd63140db847d196663a/lib/util.js#L52 turns into this in the published file:

```js
function urlGenerate(aParsedUrl) {
  var url = '';
  if (aParsedUrl.scheme) {
    url += aParsedUrl.scheme + ':';
  }
  url += '
  if (aParsedUrl.auth) {
    url += aParsedUrl.auth + '@';
  }
```

It causes this error when I try to upgrade: https://github.com/assetgraph/assetgraph/runs/4125756482?check_suite_focus=true

I'm guessing there's a naive comment scrubbing in the publication code?

**Comment by ai** [comment]
The fix https://github.com/7rulnik/source-map-js/pull/10

**Comment by 7rulnik** [comment]
fixed in https://github.com/7rulnik/source-map-js/releases/tag/v1.0.1
